config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Root path handling
  authenticated :user do
    root 'dashboard#index', as: :authenticated_root
  end

  unauthenticated do
    root 'pages#home', as: :unauthenticated_root
  end

  # Dashboard
  get 'dashboard', to: 'dashboard#index'

  # Standalone resources
  resources :projects, only: [:index]
  resources :questions, only: [:index, :create]

  # Timesheet hierarchy
  resources :timesheets, only: [:index] do
    resources :invoices, only: [:show] do
      member do
        get "generate_pdf"
      end
    end

    resources :timestamps, except: %i[index] do
      member do
        post "stop"
      end
    end
  end

  # Client hierarchy
  resources :clients, except: :destroy do
    member do
      patch :archive
      patch :restore
    end

    resources :projects, except: :destroy do
      member do
        patch :archive
        patch :restore
        patch :complete
        patch :start_tracking
      end

      resources :timesheets, except: %i[index destroy]
    end
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_lancelot_nav.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to dashboard_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png", class: "logo" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
         <!--  <%= link_to "Take a Break", questions_path, class: "nav-link" %> -->

  <!-- <div data-controller="popup">
      <%= link_to "Take a Break", questions_path, class: "btn btn-primary nav-link",
    data: {
      action: "mouseenter->popup#showPopup mouseleave->popup#hidePopup",
      popup_target: "button"
    } %>

  <div data-popup-target="popup" class="popup-image hidden">
    <img src="<%= asset_path('primary_merlin.png') %>" alt="Popup Image" class="popup-image" />
  </div>
</div>
-->

<div class="position-relative d-inline-block" data-controller="popup">
  <%= link_to questions_path,
    data: {
      action: "mouseenter->popup#showPopup mouseleave->popup#hidePopup"
    } do %>
    <%= image_tag "lance_broken.png", class: "broken_sword btn-lance" %>
  <% end %>

  <div data-popup-target="popup" class="popup-image hidden position-absolute" style="top: 100%; left: 0;">
    <img src="<%= asset_path('primary_merlin_with_text.png') %>" alt="Popup Image" class="popup-image" />
  </div>
</div>



</div>
          </li>
          <li class="nav-item">
            <% if Timestamp.last.end_time.present? %>
              <!--currently just goes to whatever the last timesheet is.. but would be good to be able to select a project-->
              <%= link_to "Stopwatch", new_timesheet_timestamp_path(Timestamp.last.timesheet), class: "nav-link" %>
            <% else %>
              <%= link_to "Stopwatch", timesheet_timestamp_path(Timestamp.last.timesheet, Timestamp.last), class: "nav-link" %>
            <% end %>
          </li>

          <li class="nav-item btn">
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link"%>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            More ;)
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Clients", clients_path, class: "dropdown-item" %></li>
            <li><%= link_to "Projects", projects_path, class: "dropdown-item" %></li>
            <li><%= link_to "Timesheets", timesheets_path, class: "dropdown-item" %></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item d-none">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar d-none" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
          <li class="nav-item">
           <%= link_to "Take a Break", questions_path, class: "nav-link" %>  <!-- here -->
          </li>
          <li class="nav-item btn">
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete} %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>